# Generated by Django 4.1.3 on 2022-11-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_skill_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_github',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_linkedin',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_twitter',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_website',
            new_name='social_website',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_youtube',
            new_name='social_youtube',
        ),
    ]
